# Generated by Django 5.1.2 on 2024-10-11 23:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(choices=[('User Typed', 'User Typed'), ('Image Combination', 'Image Combination'), ('Text Combination', 'Text Combination'), ('Text Rewrite', 'Text Rewrite')], default='User Typed', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageProducer',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(choices=[('Midjourney', 'Midjourney'), ('De3', 'De3'), ('BFL', 'BFL'), ('Ideogram', 'Ideogram')], default='BFL', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSaveType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(choices=[('Raw', 'Raw'), ('Full Annotation', 'Full Annotation'), ('Initial Idea', 'Initial Idea'), ('Final Prompt', 'Final Prompt')], default='Raw', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rewriter',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(choices=[('Claude', 'Claude')], default='Claude', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Hidden', models.BooleanField(default=False)),
                ('HideContainingPrompts', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageProducerTraits',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SaveExtension', models.CharField(max_length=255)),
                ('ImageProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imageproducer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageProducerVersion',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Version', models.CharField(max_length=255)),
                ('ImageProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imageproducer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Details', models.JSONField(default=dict)),
                ('URI', models.CharField(max_length=1024)),
                ('Result', models.JSONField(default=dict)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ImageProducerVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imageproducerversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('FilePath', models.CharField(max_length=1024)),
                ('ImageGeneration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_save', to='images.imagegeneration')),
                ('ImageSaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagesavetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('CreationTypeData', models.JSONField(default=dict, null=True)),
                ('CreationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.creationtype')),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Tags', models.ManyToManyField(related_name='prompts', to='images.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='Prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to='images.prompt'),
        ),
        migrations.CreateModel(
            name='PromptTag',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompttags', to='images.prompt')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompttags', to='images.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
