# Generated by Django 5.1.2 on 2024-10-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_prompt_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegeneration',
            name='Details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='Result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='imagesave',
            name='ImageGeneration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_saves', to='images.imagegeneration'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='CreationTypeData',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
