# Generated by Django 5.1.2 on 2024-10-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_imagegeneration_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProducer',
            new_name='ImageProducerType',
        ),
        migrations.RenameField(
            model_name='imageproducertraits',
            old_name='ImageProducer',
            new_name='ImageProducerType',
        ),
        migrations.RenameField(
            model_name='imageproducerversion',
            old_name='ImageProducer',
            new_name='ImageProducerType',
        ),
    ]
