<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MultiImageClient\MultiImageClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="3.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
