namespace RecraftAPIClient
{
    public enum RecraftDigitalIllustrationSubstyle
    {
        _2d_art_poster = 1,
        _2d_art_poster_2 = 2,
        engraving_color = 3,
        grain = 4,
        hand_drawn = 5,
        hand_drawn_outline = 6,
        handmade_3d = 7,
        infantile_sketch = 8,
        pixel_art = 9,
        antiquarian = 10,
        bold_fantasy = 11,
        child_book = 12,
        cover = 13,
        crosshatch = 14,
        digital_engraving = 15,
        expressionism = 16,
        freehand_details = 17,
        grain_20 = 18,
        graphic_intensity = 19,
        hard_comics = 20,
        long_shadow = 21,
        modern_folk = 22,
        multicolor = 23,
        neon_calm = 24,
        noir = 25,
        nostalgic_pastel = 26,
        outline_details = 27,
        pastel_gradient = 28,
        pastel_sketch = 29,
        pop_art = 30,
        pop_renaissance = 31,
        street_art = 32,
        tablet_sketch = 33,
        urban_glow = 34,
        urban_sketching = 35,
        vanilla_dreams = 36,
        young_adult_book = 37,
        young_adult_book_2 = 38,
    }
}
